/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

import org.evaluate.EvaluationVisitor;
import org.factory.NodeFactory;
import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.Test;
import org.preProcess.Parser;
import org.preProcess.Tokenizer;
import org.visitor.Node;

public class LispInterpreterTest {

    public NodeFactory factory;
    public EvaluationVisitor evaluator;

    @Before
    public void setup() {
        factory = new NodeFactory();
        evaluator = new EvaluationVisitor();
    }

    public Object eval(String input) {
        List<String> tokens = Tokenizer.tokenize(input);
        Parser parser = new Parser(tokens, factory);
        Node ast = parser.parse();

        if (parser.hasRemainingTokens()) {
            throw new RuntimeException("Unexpected token: " + parser.getCurrentToken());
        }

        return ast.accept(evaluator);
    }

    @Test
    public void testAdditionIntegers() {
        assertEquals(3, eval("(+ 1 2)"));
    }

    @Test
    public void testAdditionDouble() {
        assertEquals(4, eval("(+ 1.4 2.6)"));
    }

    @Test
    public void testMultiplicationIntegers() {
        assertEquals(6, eval("(* 2 3)"));
    }

    @Test
    public void testSubtraction() {
        assertEquals(2, eval("(- 5 3)"));
    }

    @Test
    public void testDivisionFloating() {
        assertEquals(2.5, eval("(/ 5 2)"));
    }

    @Test
    public void testMixedArithmetic() {
        assertEquals(3.5, eval("(+ 1 (/ 5 2))"));
    }

    @Test
    public void testGreaterThanTrue() {
        assertEquals(1, eval("(> 5 3)"));
    }

    @Test
    public void testGreaterThanFalse() {
        assertEquals(0, eval("(> 3 5)"));
    }

    @Test
    public void testLessThanTrue() {
        assertEquals(1, eval("(< 2 5)"));
    }

    @Test
    public void testIfTrueBranch() {
        assertEquals(10, eval("(if (> 5 3) 10 20)"));
    }

    @Test
    public void testIfFalseBranch() {
        assertEquals(20, eval("(if (< 5 3) 10 20)"));
    }

    @Test
    public void testDefineVariableWithInteger() {
        assertEquals(10, eval("(define x 10)"));
    }

    @Test
    public void testDefineVariableWithDouble() {
        assertEquals(10.0, eval("(define x 10.0)"));
    }

    @Test
    public void testVariableUsage() {
        eval("(define x 10)");
        assertEquals(15, eval("(+ x 5)"));
    }

    @Test
    public void testNestedExpression() {
        assertEquals(7, eval("(+ 1 (* 2 3))"));
    }
}
